CREATE OR REPLACE PROCEDURE DISP_EMP_DETAILS
DECLARE
    (IEMPNO IN EMPLOYEE.EMPNO%TYPE,
    SGRADE OUT EMPLOYEE.GRA%TYPE,
    SSALARY OUT EMPLOYEE.SAL%TYPE) IS
BEGIN
    SELECT GRA,SAL INTO SGRADE,SSALARY
    FROM   EMP E,SALGRADE S
    WHERE  EMPNO=IEMPNO AND E.EMPNO=S.EMPNO;
END DISP_EMP_DETAILS;
SET SERVEROUTPUT ON
DECLARE
  V_GRA EMPLOYEE.GRA%TYPE;
  V_SAL EMPLOYEE.SAL%TYPE;
BEGIN
  DISP_EMP_DETAILS(171,V_GRA,V_SAL);
  IF EMPNO !=IEMPNO
  THEN DBMS.OUPUT.PUT_LINE('employee number does not exist');
  ELSE DBMS.OUTPUT.PUT_LINE(V_GRA||'GRA'||TO_CHAR(V_SAL,'$999,999.00'));
END; 