INSERT INTO DEPARTMENT VALUES (1, 'ACCO', 'NEW YORK');
INSERT INTO DEPARTMENT VALUES (2, 'CLERK', 'DELHI');
INSERT INTO DEPARTMENT VALUES (3, 'HEALTH', 'DELHI');
INSERT INTO DEPARTMENT VALUES (4, 'THP', 'PUNE');
INSERT INTO DEPARTMENT VALUES (5, 'ANALY', 'HYD');
COMMIT;